[package]
name = "sessrums-types"
version = "0.1.0"
edition = "2021"
description = "A library implementing multiparty session types in Rust"
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
thiserror = "1.0"